apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nats-auth-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-auth-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nats-auth-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "nats-auth-operator.controllerManagerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
