apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats-auth-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-auth-operator.labels" . | nindent 4 }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    {{- toYaml .Values.metricsService.ports | nindent 4 }}
  selector:
    {{- include "nats-auth-operator.selectorLabels" . | nindent 4 }}
