{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nats-auth-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-auth-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nats-auth-operator.controllerManagerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-auth-operator.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
